-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BD_CLINICA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_CLINICA` DEFAULT CHARACTER SET utf8 ;
USE `BD_CLINICA` ;

-- -----------------------------------------------------
-- Table `BD_CLINICA`.`TB_ESPECIALIDADE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_CLINICA`.`TB_ESPECIALIDADE` ;

CREATE TABLE IF NOT EXISTS `BD_CLINICA`.`TB_ESPECIALIDADE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ESPECIALIDADE` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL COMMENT 'Nome da especialidade do médico',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `BD_CLINICA`.`TB_MEDICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_CLINICA`.`TB_MEDICO` ;

CREATE TABLE IF NOT EXISTS `BD_CLINICA`.`TB_MEDICO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ESPECIALIDADE_ID` INT NOT NULL,
  `CPF` VARCHAR(11) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `CRM` INT NOT NULL,
  `ESTADO` VARCHAR(2) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL DEFAULT 'SP',
  `DATA_NASC` DATE NOT NULL,
  `NOME` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `DDD` VARCHAR(2) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `TELEFONE` VARCHAR(9) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `SITUACAO` VARCHAR(1) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL DEFAULT 'A' COMMENT 'A - ativo\nI - inativo\n',
  `DATA_CADASTRO` DATE NOT NULL,
  `USUARIO_CADASTRO` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `DATA_ALTERACAO` DATE NOT NULL,
  `USUARIO_ALTERACAO` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_MEDICO_ESPECIALIDADE_idx` (`ESPECIALIDADE_ID` ASC) ,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) ,
  CONSTRAINT `fk_MEDICO_ESPECIALIDADE`
    FOREIGN KEY (`ESPECIALIDADE_ID`)
    REFERENCES `BD_CLINICA`.`TB_ESPECIALIDADE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `BD_CLINICA`.`TB_AGENDA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_CLINICA`.`TB_AGENDA` ;

CREATE TABLE IF NOT EXISTS `BD_CLINICA`.`TB_AGENDA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MEDICO_ID` INT NOT NULL,
  `DATA_AGENDA` DATE NOT NULL,
  `SITUACAO` VARCHAR(1) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL DEFAULT 'A' COMMENT 'A - aberta\nF - fechada\nC - cancelada',
  `DATA_CADASTRO` DATE NOT NULL,
  `USUARIO_CADASTRO` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `DATA_ALTERACAO` DATE NOT NULL,
  `USUARIO_ALTERACAO` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_TB_AGENDA_TB_MEDICO1_idx` (`MEDICO_ID` ASC) ,
  UNIQUE INDEX `ID_MEDICO_DATA_AGENDA_UNIQUE` (`MEDICO_ID` ASC, `DATA_AGENDA` ASC),
  CONSTRAINT `fk_TB_AGENDA_TB_MEDICO1`
    FOREIGN KEY (`MEDICO_ID`)
    REFERENCES `BD_CLINICA`.`TB_MEDICO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
